# Generated by Django 5.2.5 on 2025-09-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_remove_task_assignee_task_assignees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembership',
            name='joined_at',
            field=models.DateTimeField(null=True),
        ),
    ]
